# Site settings
title: Manual 1C
description: > # this means to ignore newlines until "baseurl:"
  Описание документооборота
url: 'https://lugovoe.github.io' # the base hostname & protocol for your site, e.g. http://example.com
baseurl: '/manual' # the subpath of your site, e.g. /blog

## remote method ##
remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

# Build settings
#destination: _site
#paginate: 8
#permalink: /:year/:title/
#markdown: kramdown
#highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-remote-theme
