# Site settings
title: Manual 1C
description: > # this means to ignore newlines until "baseurl:"
  Описание документооборота
url: 'https://lugovoe.github.io' # the base hostname & protocol for your site, e.g. http://example.com
baseurl: '/manual' # the subpath of your site, e.g. /blog

## remote method ##
remote_theme: rundocs/jekyll-rtd-theme

# folders sort
readme_index:
  with_frontmatter: true

meta:
  key1: value1
  key2: value2

google:
  gtag:
  adsense:

mathjax: # this will prased to json, default: {}

mermaid:
  custom:     # mermaid link
  initialize: # this will prased to json, default: {}

scss:   # also _includes/extra/styles.scss
script: # also _includes/extra/script.js

translate:
  # shortcodes
  danger:
  note:
  tip:
  warning:
  # 404
  not_found:
  # copyright
  revision:
  # search
  searching:
  search:
  search_docs:
  search_results:
  search_results_found: # the "#" in this translate will replaced with results size!
  search_results_not_found:

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-remote-theme
